//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSDRequirementsCSharp.Infrastructure.Internationalization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HelpSentences {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HelpSentences() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GSDRequirementsCSharp.Infrastructure.Internationalization.HelpSentences", typeof(HelpSentences).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access permissions for other users are granted by project..
        /// </summary>
        public static string accessPermissionsForOtherUsersAreGrantedByProject {
            get {
                return ResourceManager.GetString("accessPermissionsForOtherUsersAreGrantedByProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After adding the users and defining their profiles, you must click the &quot;Save&quot; button..
        /// </summary>
        public static string afterAddingTheUsersAndDefiningTheirProfilesYouMustClickTheSaveButton {
            get {
                return ResourceManager.GetString("afterAddingTheUsersAndDefiningTheirProfilesYouMustClickTheSaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After selecting a project in the context, menu items for managing the project data appear in the header&apos;s left side..
        /// </summary>
        public static string afterSelectingAProjectInTheContextMenuItemsForManagingTheProjectDataAppearInTheHeadersLeftSide {
            get {
                return ResourceManager.GetString("afterSelectingAProjectInTheContextMenuItemsForManagingTheProjectDataAppearInTheHe" +
                        "adersLeftSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After selecting a project in the context, the packages button will be displayed in the header&apos;s left side..
        /// </summary>
        public static string afterSelectingAProjectInTheContextThePackagesButtonWillBeDisplayedInTheHeadersLeftSide {
            get {
                return ResourceManager.GetString("afterSelectingAProjectInTheContextThePackagesButtonWillBeDisplayedInTheHeadersLef" +
                        "tSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After selecting a project in the context, the permissions button will be displayed in the header&apos;s left side..
        /// </summary>
        public static string afterSelectingAProjectInTheContextThePermissionsButtonWillBeDisplayedInTheHeadersLeftSide {
            get {
                return ResourceManager.GetString("afterSelectingAProjectInTheContextThePermissionsButtonWillBeDisplayedInTheHeaders" +
                        "LeftSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After submiting the registration data, you will be able to authenticate and manage projects..
        /// </summary>
        public static string afterSubmitingTheRegistrationDataYouWillBeAbleToAuthenticateAndManageProjects {
            get {
                return ResourceManager.GetString("afterSubmitingTheRegistrationDataYouWillBeAbleToAuthenticateAndManageProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All actions related to projects can be done only by its owner which is the user that created it..
        /// </summary>
        public static string allActionsRelatedToProjectsCanBeDoneOnlyByItsOwnerWhichIsTheUserThatCreatedIt {
            get {
                return ResourceManager.GetString("allActionsRelatedToProjectsCanBeDoneOnlyByItsOwnerWhichIsTheUserThatCreatedIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and when inserting new data the first language added will be the one selected.
        /// </summary>
        public static string andWhenInsertingNewDataTheFirstLanguageAddedWillBeTheOneSelected {
            get {
                return ResourceManager.GetString("andWhenInsertingNewDataTheFirstLanguageAddedWillBeTheOneSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artifacts are requirements, class diagrams and use case diagrams..
        /// </summary>
        public static string artifactsAreRequirementsClassDiagramsAndUseCaseDiagrams {
            get {
                return ResourceManager.GetString("artifactsAreRequirementsClassDiagramsAndUseCaseDiagrams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before you can manage projects and artifacts, you must register..
        /// </summary>
        public static string beforeYouCanManageProjectsAndArtifactsYouMustRegister {
            get {
                return ResourceManager.GetString("beforeYouCanManageProjectsAndArtifactsYouMustRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to but its possible to add translations before submitting the data.
        /// </summary>
        public static string butItsPossibleToAddTranslationBeforeSubmittingTheData {
            get {
                return ResourceManager.GetString("butItsPossibleToAddTranslationBeforeSubmittingTheData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By clicking the &quot;Edit Package&quot; button (pencil), in the package list, you will be able to edit a package..
        /// </summary>
        public static string byClickingTheEditButtonYouWillBeAbleToEditAPackage {
            get {
                return ResourceManager.GetString("byClickingTheEditButtonYouWillBeAbleToEditAPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By clicking the &quot;Edit Button&quot; (Pencil) in the project list, you will be able to edit a project..
        /// </summary>
        public static string byClickingTheEditButtonYouWillBeAbleToEditAProject {
            get {
                return ResourceManager.GetString("byClickingTheEditButtonYouWillBeAbleToEditAProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by doing so translations in the selected language will be displayed if available instead of the original data.
        /// </summary>
        public static string byDoingSoTranslationsOfTheDataWillBeDisplayedIfAvailableInsteadOfTheOriginalData {
            get {
                return ResourceManager.GetString("byDoingSoTranslationsOfTheDataWillBeDisplayedIfAvailableInsteadOfTheOriginalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can add, comment and conclude issues.
        /// </summary>
        public static string canAddCommentAndConcludeIssues {
            get {
                return ResourceManager.GetString("canAddCommentAndConcludeIssues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can add, edit, translate and exclude packages and artifacts.
        /// </summary>
        public static string canAddEditTranslateAndExcludePackagesAndArtifacts {
            get {
                return ResourceManager.GetString("canAddEditTranslateAndExcludePackagesAndArtifacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can see packages and artifacts details.
        /// </summary>
        public static string canSeePackagesAndArtifactsDetails {
            get {
                return ResourceManager.GetString("canSeePackagesAndArtifactsDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Context project.
        /// </summary>
        public static string contextProject {
            get {
                return ResourceManager.GetString("contextProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating a new package.
        /// </summary>
        public static string creatingANewPackage {
            get {
                return ResourceManager.GetString("creatingANewPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating a new project.
        /// </summary>
        public static string creatingANewProject {
            get {
                return ResourceManager.GetString("creatingANewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data inserted at first will refer to .
        /// </summary>
        public static string dataInsertedAtFirstWillReferTo {
            get {
                return ResourceManager.GetString("dataInsertedAtFirstWillReferTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data inserted at first, will refer to the current language, but it&apos;s possible to add translation before submitting the data..
        /// </summary>
        public static string dataInsertedAtFirstWillReferTotheCurrentLanguagebutItsPossibleToAddTranslationBeforeSubmittingTheData {
            get {
                return ResourceManager.GetString("dataInsertedAtFirstWillReferTotheCurrentLanguagebutItsPossibleToAddTranslationBef" +
                        "oreSubmittingTheData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing a project.
        /// </summary>
        public static string editingAProject {
            get {
                return ResourceManager.GetString("editingAProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing packages.
        /// </summary>
        public static string editingPackages {
            get {
                return ResourceManager.GetString("editingPackages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For this porpose, almost all data inserted can have a translated version..
        /// </summary>
        public static string forThisPurposeAlmostAllDataInsertedCanHaveATranslatedVersion {
            get {
                return ResourceManager.GetString("forThisPurposeAlmostAllDataInsertedCanHaveATranslatedVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Granting permissions.
        /// </summary>
        public static string grantingPermissions {
            get {
                return ResourceManager.GetString("grantingPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GSD Stands for Global Software Development, in other words, a team with members from different countries..
        /// </summary>
        public static string gsdStandsForGlobalSoftwareDevelopmentInOtherWordsATeamWithMembersFromDifferentCountries {
            get {
                return ResourceManager.GetString("gsdStandsForGlobalSoftwareDevelopmentInOtherWordsATeamWithMembersFromDifferentCou" +
                        "ntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If no translation is provided for any language, afterwards the button &quot;Add Translation&quot; will be available in the list for providing missing translations..
        /// </summary>
        public static string ifNoTranslationIsProvidedForAnyLanguageAfterwardsTheButtonAddTranslationWillBeAvailableForProvidingTheMissingTranslations {
            get {
                return ResourceManager.GetString("ifNoTranslationIsProvidedForAnyLanguageAfterwardsTheButtonAddTranslationWillBeAva" +
                        "ilableForProvidingTheMissingTranslations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the current language contains an obsolete translation.
        /// </summary>
        public static string ifTheCurrentLanguageContainsAnObsoleteTranslation {
            get {
                return ResourceManager.GetString("ifTheCurrentLanguageContainsAnObsoleteTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is a tool for requirement management aimed for global teams..
        /// </summary>
        public static string isAToolForRequirementManagementAimedForGlobalTeams {
            get {
                return ResourceManager.GetString("isAToolForRequirementManagementAimedForGlobalTeams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Its possible to change the current language pressing the change language button (globe) in the header of the page.
        /// </summary>
        public static string itsPossibleToChangeTheCurrentLanguagePressingTheChangeLanguageButtonInTheHeaderOfThePage {
            get {
                return ResourceManager.GetString("itsPossibleToChangeTheCurrentLanguagePressingTheChangeLanguageButtonInTheHeaderOf" +
                        "ThePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s possible to grant permissions by clicking the &quot;grant permission&quot; button (plus sign) in the &quot;Manage Project Permissions&quot; page.
        /// </summary>
        public static string itsPossibleToGrantPermissionsByClickingTheGrantPermissionButtonTheManageProjectPermissionsPage {
            get {
                return ResourceManager.GetString("itsPossibleToGrantPermissionsByClickingTheGrantPermissionButtonTheManageProjectPe" +
                        "rmissionsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It will lead you to the &quot;Manage Packages&quot; page, where it&apos;s possible to create, edit and remove packages..
        /// </summary>
        public static string itWillLeadYouToTheManagePackagesPageWhereItsPossibleToCreateEditAndRemovePackages {
            get {
                return ResourceManager.GetString("itWillLeadYouToTheManagePackagesPageWhereItsPossibleToCreateEditAndRemovePackages" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It will lead you to the &quot;Manage Permissions Page&quot;, where it&apos;s possible to manage the permissions of the projects that you own..
        /// </summary>
        public static string itWillLeadYouToTheManagePermissionsPageWhereItsPossibleToManageThePermissionsOfTheProjectsThatYouOwn {
            get {
                return ResourceManager.GetString("itWillLeadYouToTheManagePermissionsPageWhereItsPossibleToManageThePermissionsOfTh" +
                        "eProjectsThatYouOwn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It will provide access to a form where it&apos;s possible to add the missing translations.
        /// </summary>
        public static string itWillProvideAccessToAFormWhereItsPossibleToAddTheMissingTranslations {
            get {
                return ResourceManager.GetString("itWillProvideAccessToAFormWhereItsPossibleToAddTheMissingTranslations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next to the &quot;Manage Projects&quot; button, there&apos;s the project context control, which defines which project data is displayed..
        /// </summary>
        public static string nextToTheManageProjectButtonTheresTheProjectContextControlWhichDefinesWhichProjectDataIsDisplayed {
            get {
                return ResourceManager.GetString("nextToTheManageProjectButtonTheresTheProjectContextControlWhichDefinesWhichProjec" +
                        "tDataIsDisplayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packages that contains artifacts.
        /// </summary>
        public static string PackagesThatContainsArtifacts {
            get {
                return ResourceManager.GetString("PackagesThatContainsArtifacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission Profiles.
        /// </summary>
        public static string permissionProfiles {
            get {
                return ResourceManager.GetString("permissionProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pressing the &quot;Create Package&quot; button (plus sign) in the &quot;Manage Package&quot; screen, will lead you to the &quot;Create Package&quot; Form.
        /// </summary>
        public static string pressingTheCreatePackageButtonInTheManagePackageScreenWillLeadYouToTheCreatePackageForm {
            get {
                return ResourceManager.GetString("pressingTheCreatePackageButtonInTheManagePackageScreenWillLeadYouToTheCreatePacka" +
                        "geForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pressing the button &quot;create project&quot; (plus sign) in the &quot;Manage Project Screen&quot;, will lead you to the create project form..
        /// </summary>
        public static string pressingTheCreateProjectButtonInTheManageProjectScreenWillLeadYouToTheCreateProjectForm {
            get {
                return ResourceManager.GetString("pressingTheCreateProjectButtonInTheManageProjectScreenWillLeadYouToTheCreateProje" +
                        "ctForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project that contains packages.
        /// </summary>
        public static string ProjectThatContainsPackages {
            get {
                return ResourceManager.GetString("ProjectThatContainsPackages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing a project.
        /// </summary>
        public static string removingAProject {
            get {
                return ResourceManager.GetString("removingAProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing packages.
        /// </summary>
        public static string removingPackages {
            get {
                return ResourceManager.GetString("removingPackages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revoking permissions.
        /// </summary>
        public static string revokingPermissions {
            get {
                return ResourceManager.GetString("revokingPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the &quot;Add Translation&quot; button will be available when there are obsolete translations, to update them.
        /// </summary>
        public static string theAddTranslationButtonWillBeAvailableWhenThereAreObsoleteTranslationsToUpdateThem {
            get {
                return ResourceManager.GetString("theAddTranslationButtonWillBeAvailableWhenThereAreObsoleteTranslationsToUpdateThe" +
                        "m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the current language.
        /// </summary>
        public static string theCurrentLanguage {
            get {
                return ResourceManager.GetString("theCurrentLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to then it&apos;s necessary to search for an user by name or email, and select the profile..
        /// </summary>
        public static string thenItsNecessaryToSearchAnUserByNameOrEmailAndSelectTheProfile {
            get {
                return ResourceManager.GetString("thenItsNecessaryToSearchAnUserByNameOrEmailAndSelectTheProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project management is accessible by the manage projects button at the page header..
        /// </summary>
        public static string theProjectManagementIsAccessibleByTheManageProjectsAtThePageHeader {
            get {
                return ResourceManager.GetString("theProjectManagementIsAccessibleByTheManageProjectsAtThePageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requirement management in this tool is meant to be made collaboratively..
        /// </summary>
        public static string theRequirementsManagementInThisToolIsMeantToBeMadeCollaboratively {
            get {
                return ResourceManager.GetString("theRequirementsManagementInThisToolIsMeantToBeMadeCollaboratively", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the translations will be considered obsolete and a warning in the row will be displayed..
        /// </summary>
        public static string theTranslationsWillBeConsideredObsoleteAndAWarningInTheRowWillBeDisplayed {
            get {
                return ResourceManager.GetString("theTranslationsWillBeConsideredObsoleteAndAWarningInTheRowWillBeDisplayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user must be already registered for the permission to be granted..
        /// </summary>
        public static string theUserMustBeAlreadyRegisteredForThePermissionToBeGranted {
            get {
                return ResourceManager.GetString("theUserMustBeAlreadyRegisteredForThePermissionToBeGranted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action is irreversible.
        /// </summary>
        public static string thisActionIsIrreversible {
            get {
                return ResourceManager.GetString("thisActionIsIrreversible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This can be accomplished by pressing the &quot;Register&quot; button below the login form..
        /// </summary>
        public static string thisCanBeAccomplishedByPressingTheRegisterButtonBelowTheLoginForm {
            get {
                return ResourceManager.GetString("thisCanBeAccomplishedByPressingTheRegisterButtonBelowTheLoginForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To manage a project packages, artifacts and permissions, it must be selected in the context..
        /// </summary>
        public static string toManageAProjectPackagesArtifactsAndPermissionsItMustBeSelectedInTheContext {
            get {
                return ResourceManager.GetString("toManageAProjectPackagesArtifactsAndPermissionsItMustBeSelectedInTheContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To perform these actions, it&apos;s required to be the project&apos;s owner..
        /// </summary>
        public static string toPerformTheseActionsItsRequiredToBeTheProjectOwner {
            get {
                return ResourceManager.GetString("toPerformTheseActionsItsRequiredToBeTheProjectOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To perform these actions, it&apos;s required to have an &quot;Editor Permission&quot; in the project, or to be its owner..
        /// </summary>
        public static string toPerformTheseActionsItsRequiredToHaveAnEditorPermissionInTheProjectOrToBeItsOwner {
            get {
                return ResourceManager.GetString("toPerformTheseActionsItsRequiredToHaveAnEditorPermissionInTheProjectOrToBeItsOwne" +
                        "r", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To remove a package, it&apos;s necessary to press the &quot;Remove Package&quot; button (trash) in the package list, and confirm the action..
        /// </summary>
        public static string toRemoveAPackageItsNecessaryToPressTheRemovePackageButtonAndConfirmTheAction {
            get {
                return ResourceManager.GetString("toRemoveAPackageItsNecessaryToPressTheRemovePackageButtonAndConfirmTheAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To remove a project, it&apos;s necessary to press the &quot;Remove Project&quot; button (trash) in the project list, and confirm the action..
        /// </summary>
        public static string toRemoveAProjectItsNecessaryToPressTheRemoveProjectButtonAndConfirmTheAction {
            get {
                return ResourceManager.GetString("toRemoveAProjectItsNecessaryToPressTheRemoveProjectButtonAndConfirmTheAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To revoke a permission, you must press the &quot;Revoke Permission&quot; button (trash) in the &quot;Manage Project Permissions&quot; screen and then  click the save button..
        /// </summary>
        public static string toRevokeAPermissionYouMustPressTheRevokePermissionInTheManageProjectPermissionsScreenAndThenClickTheSaveButton {
            get {
                return ResourceManager.GetString("toRevokeAPermissionYouMustPressTheRevokePermissionInTheManageProjectPermissionsSc" +
                        "reenAndThenClickTheSaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When creating a project and not providing translation for all languages an &quot;Add Translation&quot; Button (globe) will be available in the project list..
        /// </summary>
        public static string whenCreatingAProjectAndNotProvidingTranslationForAllLanguagesAnAddTranslationButtonWillBeAvailable {
            get {
                return ResourceManager.GetString("whenCreatingAProjectAndNotProvidingTranslationForAllLanguagesAnAddTranslationButt" +
                        "onWillBeAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When editing a package with translations, but not updating them.
        /// </summary>
        public static string whenEditingAPackageWithTranslationsButNotUpdatingThem {
            get {
                return ResourceManager.GetString("whenEditingAPackageWithTranslationsButNotUpdatingThem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When editing a project with translations, but not updating them.
        /// </summary>
        public static string whenEditingAProjectWithTranslationsButNotUpdatingThem {
            get {
                return ResourceManager.GetString("whenEditingAProjectWithTranslationsButNotUpdatingThem", resourceCulture);
            }
        }
    }
}
