//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSDRequirementsCSharp.Infrastructure.Internationalization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Sentences {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Sentences() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GSDRequirementsCSharp.Infrastructure.Internationalization.Sentences", typeof(Sentences).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string action {
            get {
                return ResourceManager.GetString("action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string actions {
            get {
                return ResourceManager.GetString("actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add issue.
        /// </summary>
        public static string addIssue {
            get {
                return ResourceManager.GetString("addIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new version.
        /// </summary>
        public static string addNewVersion {
            get {
                return ResourceManager.GetString("addNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add package.
        /// </summary>
        public static string addPackage {
            get {
                return ResourceManager.GetString("addPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add permissions.
        /// </summary>
        public static string addPermissions {
            get {
                return ResourceManager.GetString("addPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add project.
        /// </summary>
        public static string addProject {
            get {
                return ResourceManager.GetString("addProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add requirement.
        /// </summary>
        public static string addRequirement {
            get {
                return ResourceManager.GetString("addRequirement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add translation.
        /// </summary>
        public static string addTranslation {
            get {
                return ResourceManager.GetString("addTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add translation for package.
        /// </summary>
        public static string addTranslationForPackage {
            get {
                return ResourceManager.GetString("addTranslationForPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add translation for project.
        /// </summary>
        public static string addTranslationForProject {
            get {
                return ResourceManager.GetString("addTranslationForProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add translation for requirement.
        /// </summary>
        public static string addTranslationForRequirement {
            get {
                return ResourceManager.GetString("addTranslationForRequirement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All translation added.
        /// </summary>
        public static string allTranslationsAdded {
            get {
                return ResourceManager.GetString("allTranslationsAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artifacts.
        /// </summary>
        public static string artifacts {
            get {
                return ResourceManager.GetString("artifacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticate.
        /// </summary>
        public static string authenticate {
            get {
                return ResourceManager.GetString("authenticate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication.
        /// </summary>
        public static string authentication {
            get {
                return ResourceManager.GetString("authentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication failed.
        /// </summary>
        public static string authenticationFailed {
            get {
                return ResourceManager.GetString("authenticationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change language.
        /// </summary>
        public static string changeLanguage {
            get {
                return ResourceManager.GetString("changeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change project in context.
        /// </summary>
        public static string changeProjectInContext {
            get {
                return ResourceManager.GetString("changeProjectInContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a language.
        /// </summary>
        public static string chooseALanguage {
            get {
                return ResourceManager.GetString("chooseALanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class diagrams.
        /// </summary>
        public static string classDiagrams {
            get {
                return ResourceManager.GetString("classDiagrams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collaborator.
        /// </summary>
        public static string collaborator {
            get {
                return ResourceManager.GetString("collaborator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition.
        /// </summary>
        public static string condition {
            get {
                return ResourceManager.GetString("condition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string confirmPassword {
            get {
                return ResourceManager.GetString("confirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new Account.
        /// </summary>
        public static string createNewAccount {
            get {
                return ResourceManager.GetString("createNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create package.
        /// </summary>
        public static string createPackage {
            get {
                return ResourceManager.GetString("createPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create project.
        /// </summary>
        public static string createProject {
            get {
                return ResourceManager.GetString("createProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current project.
        /// </summary>
        public static string currentProject {
            get {
                return ResourceManager.GetString("currentProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difficulty.
        /// </summary>
        public static string difficulty {
            get {
                return ResourceManager.GetString("difficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easy.
        /// </summary>
        public static string easy {
            get {
                return ResourceManager.GetString("easy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor.
        /// </summary>
        public static string editor {
            get {
                return ResourceManager.GetString("editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit package.
        /// </summary>
        public static string editPackage {
            get {
                return ResourceManager.GetString("editPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit project.
        /// </summary>
        public static string editProject {
            get {
                return ResourceManager.GetString("editProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit requirement.
        /// </summary>
        public static string editRequirement {
            get {
                return ResourceManager.GetString("editRequirement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit translation.
        /// </summary>
        public static string editTranslation {
            get {
                return ResourceManager.GetString("editTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error adding translation.
        /// </summary>
        public static string errorAddingTranslation {
            get {
                return ResourceManager.GetString("errorAddingTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error granting permissions.
        /// </summary>
        public static string errorGrantingPermissions {
            get {
                return ResourceManager.GetString("errorGrantingPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error inactivating package.
        /// </summary>
        public static string errorInactivatingPackage {
            get {
                return ResourceManager.GetString("errorInactivatingPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error inactivating project.
        /// </summary>
        public static string errorInactivatingProject {
            get {
                return ResourceManager.GetString("errorInactivatingProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error inactivating requirement.
        /// </summary>
        public static string errorInactivatingRequirement {
            get {
                return ResourceManager.GetString("errorInactivatingRequirement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading packages.
        /// </summary>
        public static string errorLoadingPackages {
            get {
                return ResourceManager.GetString("errorLoadingPackages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading permissions.
        /// </summary>
        public static string errorLoadingPermissions {
            get {
                return ResourceManager.GetString("errorLoadingPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading projects.
        /// </summary>
        public static string errorLoadingProjects {
            get {
                return ResourceManager.GetString("errorLoadingProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading requirements.
        /// </summary>
        public static string errorLoadingRequirements {
            get {
                return ResourceManager.GetString("errorLoadingRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving package.
        /// </summary>
        public static string errorSavingPackage {
            get {
                return ResourceManager.GetString("errorSavingPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving project.
        /// </summary>
        public static string errorSavingProject {
            get {
                return ResourceManager.GetString("errorSavingProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving requirement.
        /// </summary>
        public static string errorSavingRequirement {
            get {
                return ResourceManager.GetString("errorSavingRequirement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving user account.
        /// </summary>
        public static string errorSavingUserAccount {
            get {
                return ResourceManager.GetString("errorSavingUserAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error searching users.
        /// </summary>
        public static string errorSearchingUsers {
            get {
                return ResourceManager.GetString("errorSearchingUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by name.
        /// </summary>
        public static string filterByName {
            get {
                return ResourceManager.GetString("filterByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Functional.
        /// </summary>
        public static string functional {
            get {
                return ResourceManager.GetString("functional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hard.
        /// </summary>
        public static string hard {
            get {
                return ResourceManager.GetString("hard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string id {
            get {
                return ResourceManager.GetString("id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactivate package.
        /// </summary>
        public static string inactivatePackage {
            get {
                return ResourceManager.GetString("inactivatePackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactivate project.
        /// </summary>
        public static string inactivateProject {
            get {
                return ResourceManager.GetString("inactivateProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid items.
        /// </summary>
        public static string invalidItems {
            get {
                return ResourceManager.GetString("invalidItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Password.
        /// </summary>
        public static string invalidPassword {
            get {
                return ResourceManager.GetString("invalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string logout {
            get {
                return ResourceManager.GetString("logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage links.
        /// </summary>
        public static string manageLinks {
            get {
                return ResourceManager.GetString("manageLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage packages.
        /// </summary>
        public static string managePackages {
            get {
                return ResourceManager.GetString("managePackages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage profiles.
        /// </summary>
        public static string manageProfiles {
            get {
                return ResourceManager.GetString("manageProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage projects.
        /// </summary>
        public static string manageProjects {
            get {
                return ResourceManager.GetString("manageProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage project users.
        /// </summary>
        public static string manageProjectUsers {
            get {
                return ResourceManager.GetString("manageProjectUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage users.
        /// </summary>
        public static string manageUsers {
            get {
                return ResourceManager.GetString("manageUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        public static string medium {
            get {
                return ResourceManager.GetString("medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile phone.
        /// </summary>
        public static string mobilePhone {
            get {
                return ResourceManager.GetString("mobilePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must allow access permission management.
        /// </summary>
        public static string mustAllowAccessPermissionManagement {
            get {
                return ResourceManager.GetString("mustAllowAccessPermissionManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is a required field.
        /// </summary>
        public static string nameIsARequiredField {
            get {
                return ResourceManager.GetString("nameIsARequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non functional.
        /// </summary>
        public static string nonFunction {
            get {
                return ResourceManager.GetString("nonFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No package registered.
        /// </summary>
        public static string noPackageRegistered {
            get {
                return ResourceManager.GetString("noPackageRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No permission registered.
        /// </summary>
        public static string noPermissionRegistered {
            get {
                return ResourceManager.GetString("noPermissionRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No project in context.
        /// </summary>
        public static string noProjectInContext {
            get {
                return ResourceManager.GetString("noProjectInContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No project registered.
        /// </summary>
        public static string noProjectRegistered {
            get {
                return ResourceManager.GetString("noProjectRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No requirement registered.
        /// </summary>
        public static string noRequirementRegistered {
            get {
                return ResourceManager.GetString("noRequirementRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results.
        /// </summary>
        public static string noResults {
            get {
                return ResourceManager.GetString("noResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No translation added.
        /// </summary>
        public static string noTranslationAdded {
            get {
                return ResourceManager.GetString("noTranslationAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observer.
        /// </summary>
        public static string observer {
            get {
                return ResourceManager.GetString("observer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original.
        /// </summary>
        public static string original {
            get {
                return ResourceManager.GetString("original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package.
        /// </summary>
        public static string package {
            get {
                return ResourceManager.GetString("package", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package inactivated successfully.
        /// </summary>
        public static string packageInactivatedSuccessfully {
            get {
                return ResourceManager.GetString("packageInactivatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package not found.
        /// </summary>
        public static string packageNotFound {
            get {
                return ResourceManager.GetString("packageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packages.
        /// </summary>
        public static string packages {
            get {
                return ResourceManager.GetString("packages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package successfully created.
        /// </summary>
        public static string packageSuccessfullyCreated {
            get {
                return ResourceManager.GetString("packageSuccessfullyCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package updated successfully.
        /// </summary>
        public static string packageUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("packageUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password and confirmation must match.
        /// </summary>
        public static string passwordAndConfirmationMustMatch {
            get {
                return ResourceManager.GetString("passwordAndConfirmationMustMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions.
        /// </summary>
        public static string permissions {
            get {
                return ResourceManager.GetString("permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions successfully granted.
        /// </summary>
        public static string permissionsSuccessfullyGranted {
            get {
                return ResourceManager.GetString("permissionsSuccessfullyGranted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string phone {
            get {
                return ResourceManager.GetString("phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string profile {
            get {
                return ResourceManager.GetString("profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project inactivated successfully.
        /// </summary>
        public static string projectInactivatedSuccessfully {
            get {
                return ResourceManager.GetString("projectInactivatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project not found.
        /// </summary>
        public static string projectNotFound {
            get {
                return ResourceManager.GetString("projectNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project owner.
        /// </summary>
        public static string projectOwner {
            get {
                return ResourceManager.GetString("projectOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        public static string projects {
            get {
                return ResourceManager.GetString("projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project successfully created.
        /// </summary>
        public static string projectSuccessfullyCreated {
            get {
                return ResourceManager.GetString("projectSuccessfullyCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project updated successfully.
        /// </summary>
        public static string projectUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("projectUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank.
        /// </summary>
        public static string rank {
            get {
                return ResourceManager.GetString("rank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string register {
            get {
                return ResourceManager.GetString("register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove requirement.
        /// </summary>
        public static string removeRequirement {
            get {
                return ResourceManager.GetString("removeRequirement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove translation.
        /// </summary>
        public static string removeTranslation {
            get {
                return ResourceManager.GetString("removeTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        public static string report {
            get {
                return ResourceManager.GetString("report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requirement inactivated successfully.
        /// </summary>
        public static string requirementInactivatedSuccessfully {
            get {
                return ResourceManager.GetString("requirementInactivatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requirements.
        /// </summary>
        public static string requirements {
            get {
                return ResourceManager.GetString("requirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requirement successfully created.
        /// </summary>
        public static string requirementSuccessfullyCreated {
            get {
                return ResourceManager.GetString("requirementSuccessfullyCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requirement updated successfully.
        /// </summary>
        public static string requirementUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("requirementUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for an user by name or email.
        /// </summary>
        public static string searchForAnUserByNameOrEmail {
            get {
                return ResourceManager.GetString("searchForAnUserByNameOrEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See pending Issues.
        /// </summary>
        public static string seePendingIssues {
            get {
                return ResourceManager.GetString("seePendingIssues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show details and manage versions.
        /// </summary>
        public static string showDetailsAndManageVersions {
            get {
                return ResourceManager.GetString("showDetailsAndManageVersions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string subject {
            get {
                return ResourceManager.GetString("subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The system.
        /// </summary>
        public static string theSystem {
            get {
                return ResourceManager.GetString("theSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traceability matrix.
        /// </summary>
        public static string traceabilityMatrix {
            get {
                return ResourceManager.GetString("traceabilityMatrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation.
        /// </summary>
        public static string translation {
            get {
                return ResourceManager.GetString("translation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation added successfully.
        /// </summary>
        public static string translationAddedSuccessfully {
            get {
                return ResourceManager.GetString("translationAddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translations.
        /// </summary>
        public static string translations {
            get {
                return ResourceManager.GetString("translations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translations is outdated.
        /// </summary>
        public static string translationsIsOutdated {
            get {
                return ResourceManager.GetString("translationsIsOutdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string type {
            get {
                return ResourceManager.GetString("type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string undo {
            get {
                return ResourceManager.GetString("undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use case diagrams.
        /// </summary>
        public static string useCaseDiagrams {
            get {
                return ResourceManager.GetString("useCaseDiagrams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string user {
            get {
                return ResourceManager.GetString("user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User account successfully created.
        /// </summary>
        public static string userAccountSuccessfullyCreated {
            get {
                return ResourceManager.GetString("userAccountSuccessfullyCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found.
        /// </summary>
        public static string userNotFound {
            get {
                return ResourceManager.GetString("userNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string version {
            get {
                return ResourceManager.GetString("version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When the user is an administrator.
        /// </summary>
        public static string whenTheUserIsAnAdministrator {
            get {
                return ResourceManager.GetString("whenTheUserIsAnAdministrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permission to access this project.
        /// </summary>
        public static string youDontHavePermissionToAccessThisProject {
            get {
                return ResourceManager.GetString("youDontHavePermissionToAccessThisProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must be logged in.
        /// </summary>
        public static string youMustBeLoggedIn {
            get {
                return ResourceManager.GetString("youMustBeLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must be the project owner to execute this action.
        /// </summary>
        public static string youMustBeTheProjectOwnerToExecuteThisAction {
            get {
                return ResourceManager.GetString("youMustBeTheProjectOwnerToExecuteThisAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must have editor permission for this project to execute this action.
        /// </summary>
        public static string youMustHaveEditorPermissionForThisProjectToExecuteThisAction {
            get {
                return ResourceManager.GetString("youMustHaveEditorPermissionForThisProjectToExecuteThisAction", resourceCulture);
            }
        }
    }
}
