//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSDRequirementsCSharp.Infrastructure.Internationalization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GSDRequirementsCSharp.Infrastructure.Internationalization.ValidationMessages", typeof(ValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max &quot;Action&quot; length is 150.
        /// </summary>
        public static string actionMaxLengthIs150 {
            get {
                return ResourceManager.GetString("actionMaxLengthIs150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Class Diagram Id&quot; is a required field.
        /// </summary>
        public static string classDiagramIdIsRequiredField {
            get {
                return ResourceManager.GetString("classDiagramIdIsRequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Class Type&quot; is a required field.
        /// </summary>
        public static string classTypeIsARequiredField {
            get {
                return ResourceManager.GetString("classTypeIsARequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max &quot;Condition&quot; length is 150.
        /// </summary>
        public static string conditionMaxLengthIs150 {
            get {
                return ResourceManager.GetString("conditionMaxLengthIs150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Description&quot; is a required field.
        /// </summary>
        public static string descriptionIsARequiredField {
            get {
                return ResourceManager.GetString("descriptionIsARequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Difficulty&quot; is a required field.
        /// </summary>
        public static string difficultyIsARequiredField {
            get {
                return ResourceManager.GetString("difficultyIsARequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email field must have a valid email address.
        /// </summary>
        public static string emailFieldMustHaveAValidEmailAddress {
            get {
                return ResourceManager.GetString("emailFieldMustHaveAValidEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Email&quot; is a required field.
        /// </summary>
        public static string emailIsARequiredField {
            get {
                return ResourceManager.GetString("emailIsARequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Issue comment id&quot; is a required field.
        /// </summary>
        public static string issueCommentIdIsARequiredField {
            get {
                return ResourceManager.GetString("issueCommentIdIsARequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Issue Id&quot; is a required field.
        /// </summary>
        public static string issueIdIsARequiredField {
            get {
                return ResourceManager.GetString("issueIdIsARequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Locale&quot; is a required field.
        /// </summary>
        public static string localeIsARequiredField {
            get {
                return ResourceManager.GetString("localeIsARequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Login&quot; is a required field.
        /// </summary>
        public static string loginIsARequiredField {
            get {
                return ResourceManager.GetString("loginIsARequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max &quot;Email&quot; length is 50.
        /// </summary>
        public static string maxEmailLengthIs50 {
            get {
                return ResourceManager.GetString("maxEmailLengthIs50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max &quot;Login&quot; length is 50.
        /// </summary>
        public static string maxLoginLengthIs50 {
            get {
                return ResourceManager.GetString("maxLoginLengthIs50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max &quot;Mobile Phone&quot; length is 20.
        /// </summary>
        public static string maxMobilePhoneLengthIs50 {
            get {
                return ResourceManager.GetString("maxMobilePhoneLengthIs50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max &quot;Name&quot; length is 100.
        /// </summary>
        public static string maxNameLengthIs100 {
            get {
                return ResourceManager.GetString("maxNameLengthIs100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max &quot;Password&quot; length is 50.
        /// </summary>
        public static string maxPasswordLengthIs50 {
            get {
                return ResourceManager.GetString("maxPasswordLengthIs50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max &quot;Phone&quot; length is 50.
        /// </summary>
        public static string maxPhoneLengthIs20 {
            get {
                return ResourceManager.GetString("maxPhoneLengthIs20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Method visibility&quot; is a required field.
        /// </summary>
        public static string methodVisibilityIsARequiredField {
            get {
                return ResourceManager.GetString("methodVisibilityIsARequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimun &quot;Password&quot; length is 4.
        /// </summary>
        public static string minPasswordLengthIs4 {
            get {
                return ResourceManager.GetString("minPasswordLengthIs4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Mobile Phone&quot; must contain only numbers.
        /// </summary>
        public static string mobilePhoneMustContainOnlyNumbers {
            get {
                return ResourceManager.GetString("mobilePhoneMustContainOnlyNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Name&quot; is a required field.
        /// </summary>
        public static string nameIsARequiredField {
            get {
                return ResourceManager.GetString("nameIsARequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Origin&quot; is a required field.
        /// </summary>
        public static string originIsARequiredField {
            get {
                return ResourceManager.GetString("originIsARequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Package Id&quot; is a required field.
        /// </summary>
        public static string packageIdIsARequiredField {
            get {
                return ResourceManager.GetString("packageIdIsARequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Package&quot; is a required field.
        /// </summary>
        public static string packageIsARequiredField {
            get {
                return ResourceManager.GetString("packageIsARequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Parameter Name&quot; is a required field.
        /// </summary>
        public static string parameterNameIsARequiredField {
            get {
                return ResourceManager.GetString("parameterNameIsARequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Parameter Type&quot; is a required field.
        /// </summary>
        public static string parameterTypeIsARequiredField {
            get {
                return ResourceManager.GetString("parameterTypeIsARequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Password&quot; is a required field.
        /// </summary>
        public static string passwordIsARequiredField {
            get {
                return ResourceManager.GetString("passwordIsARequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Phone&quot; must contain only numbers.
        /// </summary>
        public static string phoneMustContainOnlyNumbers {
            get {
                return ResourceManager.GetString("phoneMustContainOnlyNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Project id&quot; is a required field.
        /// </summary>
        public static string projectIdIsARequiredField {
            get {
                return ResourceManager.GetString("projectIdIsARequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Propert Name&quot; is a required field.
        /// </summary>
        public static string propertyNameIsARequiredField {
            get {
                return ResourceManager.GetString("propertyNameIsARequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Property Type&quot; is a required field.
        /// </summary>
        public static string propertyTypeIsARequiredField {
            get {
                return ResourceManager.GetString("propertyTypeIsARequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Property Visibility&quot; is a required field.
        /// </summary>
        public static string propertyVisibilityIsARequiredField {
            get {
                return ResourceManager.GetString("propertyVisibilityIsARequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Rank&quot; is a required field.
        /// </summary>
        public static string rankIsARequiredField {
            get {
                return ResourceManager.GetString("rankIsARequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Requirement id&quot; is a required field.
        /// </summary>
        public static string requirementIdIsARequiredField {
            get {
                return ResourceManager.GetString("requirementIdIsARequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Requirement&quot; is a required field.
        /// </summary>
        public static string requirementIsARequiredField {
            get {
                return ResourceManager.GetString("requirementIsARequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Requirement type&quot; is a required field.
        /// </summary>
        public static string requirementTypeIsARequiredField {
            get {
                return ResourceManager.GetString("requirementTypeIsARequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Return Type&quot; is a required field.
        /// </summary>
        public static string returnTypeIsARequiredField {
            get {
                return ResourceManager.GetString("returnTypeIsARequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Source&quot; is a required field.
        /// </summary>
        public static string sourceIsARequiredField {
            get {
                return ResourceManager.GetString("sourceIsARequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Specification item id&quot; is a required field.
        /// </summary>
        public static string specificationItemIdIsARequiredField {
            get {
                return ResourceManager.GetString("specificationItemIdIsARequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Specification item&quot; is a required field.
        /// </summary>
        public static string specificationItemIsARequiredField {
            get {
                return ResourceManager.GetString("specificationItemIsARequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max &quot;Subject&quot; length is 150.
        /// </summary>
        public static string subjectMaxLengthIs150 {
            get {
                return ResourceManager.GetString("subjectMaxLengthIs150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Target&quot; is a required field.
        /// </summary>
        public static string targetIsARequiredField {
            get {
                return ResourceManager.GetString("targetIsARequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;User Id&quot; is a required field.
        /// </summary>
        public static string userIdIsARequiredField {
            get {
                return ResourceManager.GetString("userIdIsARequiredField", resourceCulture);
            }
        }
    }
}
