// <auto-generated />
namespace GSDRequirementsCSharp.Persistence.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class removeusecasespecificationitemrelation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removeusecasespecificationitemrelation));
        
        string IMigrationMetadata.Id
        {
            get { return "201605061255424_remove-use-case-specification-item-relation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
