// <auto-generated />
namespace GSDRequirementsCSharp.Persistence.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class classmethodreturntyperequired : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(classmethodreturntyperequired));
        
        string IMigrationMetadata.Id
        {
            get { return "201604042350384_class-method-return-type-required"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
