// <auto-generated />
namespace GSDRequirementsCSharp.Persistence.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class classdiagram : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(classdiagram));
        
        string IMigrationMetadata.Id
        {
            get { return "201604261149252_class-diagram"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
